// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrZ0NW2kN5eZeg87SSPv-PyCp_BjL-WL8',
    appId: '1:235935531401:web:64faab8d5ce5995eeb6158',
    messagingSenderId: '235935531401',
    projectId: 'chatappprac-d7a2b',
    authDomain: 'chatappprac-d7a2b.firebaseapp.com',
    storageBucket: 'chatappprac-d7a2b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKcNAY-1gPUrmzrgYQMtAD5qk5hhiACcU',
    appId: '1:235935531401:android:b9a7af57ba24dacaeb6158',
    messagingSenderId: '235935531401',
    projectId: 'chatappprac-d7a2b',
    storageBucket: 'chatappprac-d7a2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlvYGszBtCOUH_Gb8YFlPDquCvIKonG9U',
    appId: '1:235935531401:ios:00f0821746878895eb6158',
    messagingSenderId: '235935531401',
    projectId: 'chatappprac-d7a2b',
    storageBucket: 'chatappprac-d7a2b.appspot.com',
    iosBundleId: 'com.example.upai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlvYGszBtCOUH_Gb8YFlPDquCvIKonG9U',
    appId: '1:235935531401:ios:00f0821746878895eb6158',
    messagingSenderId: '235935531401',
    projectId: 'chatappprac-d7a2b',
    storageBucket: 'chatappprac-d7a2b.appspot.com',
    iosBundleId: 'com.example.upai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrZ0NW2kN5eZeg87SSPv-PyCp_BjL-WL8',
    appId: '1:235935531401:web:89bcce091445d5cdeb6158',
    messagingSenderId: '235935531401',
    projectId: 'chatappprac-d7a2b',
    authDomain: 'chatappprac-d7a2b.firebaseapp.com',
    storageBucket: 'chatappprac-d7a2b.appspot.com',
  );
}
